[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "mlfqa"
authors = [
  {name = "Shane Arora", email = "shane.arora@utexas.edu"},
]
description = "Multilingual Long-Form QA"
readme = "README.md"