[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "mlfqa"
authors = [
  {name = "Shane Arora", email = "shane.arora@utexas.edu"},
]
description = "Multilingual Long-Form QA"
readme = "README.md"
dependencies = [
  "accelerate",
  "openai",
  "pydantic",
  "python-dotenv",
  "torch",
  "transformers",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  # Missing doc strings
  "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
  # Missing self type check
  "ANN101",
  # Asserts
  "S101",
]